# Generated by Django 4.2.29 on 2026-03-14 23:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking_status_passengerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
